name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      cli:
        description: Run by cypress command line
        default: npx cypress run

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:12.2.0
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v4.2.2

      - name: Print working directory
        run: pwd

      - name: List test files
        run: ls -R cypress/e2e

      - name: Install dependencies
        run: npm install

      - name: Run E2E tests
        run: ${{ github.event.inputs.cli }}
